version: '3.9'
name: 'robocup_pkg'

services:
  scene:
    image: robocup_pkg:latest
    container_name: youbot
    build:
      context: ./
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./robocup_pkg:/ros_ws/src/robocup_pkg
      - ./rpg_svo_pro_open:/ros_ws/src/svo_pkg/rpg_svo_pro_open

